//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerticalSlice.Api.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerticalSlice.Api.Shared.Resources.SharedResource.pt-BR", typeof(SharedResource_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tivemos um problema ao processar a sua solicitação.
        /// </summary>
        internal static string DefaultApiError {
            get {
                return ResourceManager.GetString("DefaultApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado.
        /// </summary>
        internal static string UserDisplayNameEmpty {
            get {
                return ResourceManager.GetString("UserDisplayNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ter entre 3 em 50 caracteres.
        /// </summary>
        internal static string UserDisplayNameInvalidLength {
            get {
                return ResourceManager.GetString("UserDisplayNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário já existe.
        /// </summary>
        internal static string UserEmailAlreadyExists {
            get {
                return ResourceManager.GetString("UserEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ser informado.
        /// </summary>
        internal static string UserEmailEmpty {
            get {
                return ResourceManager.GetString("UserEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário está em um formato inválido.
        /// </summary>
        internal static string UserEmailInvalidFormat {
            get {
                return ResourceManager.GetString("UserEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ter entre 3 e 50 caracteres.
        /// </summary>
        internal static string UserEmailInvalidLength {
            get {
                return ResourceManager.GetString("UserEmailInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id da organização deve ser informado.
        /// </summary>
        internal static string UserOrganizationIdEmpty {
            get {
                return ResourceManager.GetString("UserOrganizationIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A organização não foi encontrada.
        /// </summary>
        internal static string UserOrganizationNotFound {
            get {
                return ResourceManager.GetString("UserOrganizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role do usuário deve ser informada.
        /// </summary>
        internal static string UserRoleIdEmpty {
            get {
                return ResourceManager.GetString("UserRoleIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role não foi encontrada.
        /// </summary>
        internal static string UserRoleNotFound {
            get {
                return ResourceManager.GetString("UserRoleNotFound", resourceCulture);
            }
        }
    }
}
